export const SET_USER = 'SET_USER';
export const SET_ISLOADING = 'SET_ISLOADING';
export const ADD_CHANNELS = 'SET_CHANNEL';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_SELECTED= 'SET_SELECTED';